export const mapeo: any = {
  modulo: "general",
  modelo: "guia",
  tipo: "Movimiento",
  datos: [
    {
      nombre: "ID",
      campoTipo: "IntegerField",
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: "Guia",
      campoTipo: "IntegerField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Fecha",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: "Documento",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Destinatario",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: "Dirección",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: " Teléfono",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Correo",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Peso",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Volumen",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Latitud",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Longitud",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Orden",
      campoTipo: "IntegerField",
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: "Distancia",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
  ],
};
