export const mapeo: any = {
  modulo: "general",
  modelo: "guia",
  tipo: "Movimiento",
  datos: [
    {
      nombre: "ID",
      campoTipo: "IntegerField",
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: "Guia",
      campoTipo: "IntegerField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Fecha",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: "Documento",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Destinatario",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: "Destinatario dirección",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Destinatario telefono",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Destinatario correo",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Peso",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Volumen",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Decodificado",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Latitud",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Longitud",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    }
  ],
};
