export const mapeo: any = {
  modulo: "general",
  modelo: "contacto",
  tipo: "Administrador",
  datos: [
    {
      nombre: "ID",
      campoTipo: "IntegerField",
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: "Tipo",
      campoTipo: "IntegerField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Número de identificación",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: "Digito verificación",
      campoTipo: "CharField",
      visibleTabla: false,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Nombre",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: true,
      ordenable: true,
    },
    {
      nombre: "Correo",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Dirección",
      campoTipo: "CharField",
      visibleTabla: false,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Nombre1",
      campoTipo: "CharField",
      visibleTabla: false,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Nombre2",
      campoTipo: "CharField",
      visibleTabla: false,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Apellido1",
      campoTipo: "CharField",
      visibleTabla: false,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Apellido2",
      campoTipo: "CharField",
      visibleTabla: false,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Código postal",
      campoTipo: "CharField",
      visibleTabla: false,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Teléfono",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Celular",
      campoTipo: "CharField",
      visibleTabla: true,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Barrio",
      campoTipo: "CharField",
      visibleTabla: false,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Código ciuu",
      campoTipo: "CharField",
      visibleTabla: false,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Ciudad nombre",
      campoTipo: "CharField",
      visibleTabla: false,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Regimen",
      campoTipo: "CharField",
      visibleTabla: false,
      visibleFiltro: false,
      ordenable: false,
    },
    {
      nombre: "Tipo persona",
      campoTipo: "CharField",
      visibleTabla: false,
      visibleFiltro: false,
      ordenable: false,
    },
  ],
};
